### ISSUE TITLE
[documentation] packaging 

### ISSUE THREAD

**Issue by 4383** [AntoineCezar/cookiecutter-pypkg#10]
Each kind of packaging must be documented for final users.
Each documentation must describe how to share packaging file (spec, APKBUILD, etc...) with distributions repositories.

Example with alpine linux:
- fork https://github.com/alpinelinux/aports
- propose or update a new package
- etc...

**Comment by AntoineCezar** [comment]
This will lead to add and maintain each supported distribution. Seems a lot of work.

**Comment by 4383** [comment]
Yep or just add some links to refer the user actions needed after that. [CI](https://github.com/4383/bookmarks/blob/master/.travis.yml) can help you to maintain dead links automaticaly [like this project](https://github.com/4383/bookmarks/tree/master/.travis).
Community can be help us when this project grow up, I let's you choose the right way ;)

**Comment by AntoineCezar** [comment]
Packaging documentation will be adressed in each packaging ticket.
