### ISSUE TITLE
feature request - also packaging in deb rpm... format

### ISSUE THREAD

**Issue by 4383** [AntoineCezar/cookiecutter-pypkg#3]
Hello guys!

Create this template from scratch is a good point!
We want (@dj4ngo and myself) to help you to introduce standard software behaviors like system packaging management (rpm, deb, etc...).

We can introduce automatic deployment of different kind of packages to the officials packages repositories like alpine linux and others. CI/CD can be used for push package updates automaticaly when a tag are created with synchronized version number anytime and development version. So a fork of main distributions packages repositories ([aports](https://github.com/alpinelinux/aports/pulls))must be created and keep up to date for and push our new versions automaticaly.

Are you interested by this feature?

**Comment by AntoineCezar** [comment]
Thank for your help.

Package building is an interesting feature.

CI/CD and automatic deployment might lead to a dread project setup with way too many options. So it will be an opinionated choice.

**Comment by AntoineCezar** [comment]
opened separate issues:
- #5 build rpm
- #6 build deb
